steps:

- task: MicroBuildIBCMergePlugin@0
  inputs:
    branch: rel/d15.8
  displayName: Install MicroBuild IBCMerge Plugin
  enabled: false

- task: MicroBuildSigningPlugin@3
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  enabled: false
